name: pananno_jsarria
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohttp=3.7.4.post0=py39h3811e60_1
  - alsa-lib=1.2.8=h166bdaf_0
  - amply=0.1.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argcomplete=3.1.1=pyhd8ed1ab_0
  - argh=0.27.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - backports.zoneinfo=0.2.1=py39hf3d152e_7
  - bcrypt=3.2.2=py39hb9d737c_1
  - bedtools=2.31.0=hf5e1c6e_2
  - biopython=1.81=py39h72bdee0_0
  - blast=2.14.0=h7d5a4b4_1
  - boltons=23.0.0=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h6582d0a_3
  - boto3=1.26.140=pyhd8ed1ab_0
  - botocore=1.29.140=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=hbbf8b49_1016
  - cdbtools=0.99=hdcf5f25_9
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - chardet=4.0.0=py39hf3d152e_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - colour=0.1.5=py_0
  - conda=23.3.1=py39hf3d152e_0
  - conda-package-handling=2.0.2=
