name: pananno_jsarria
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohttp=3.7.4.post0=py39h3811e60_1
  - alsa-lib=1.2.8=h166bdaf_0
  - amply=0.1.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argcomplete=3.1.1=pyhd8ed1ab_0
  - argh=0.27.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.12.1=pyhd8ed1ab_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - backports.zoneinfo=0.2.1=py39hf3d152e_7
  - bcrypt=3.2.2=py39hb9d737c_1
  - bedtools=2.31.0=hf5e1c6e_2
  - biopython=1.81=py39h72bdee0_0
  - blast=2.14.0=h7d5a4b4_1
  - boltons=23.0.0=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h6582d0a_3
  - boto3=1.26.140=pyhd8ed1ab_0
  - botocore=1.29.140=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=hbbf8b49_1016
  - cdbtools=0.99=hdcf5f25_9
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - chardet=4.0.0=py39hf3d152e_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - colour=0.1.5=py_0
  - conda=23.3.1=py39hf3d152e_0
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.7.0=pyhd8ed1ab_1
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=39.0.0=py39hd598818_0
  - curl=7.87.0=h6312ad2_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datrie=0.8.2=py39hb9d737c_6
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diamond=2.1.8=h43eeafb_0
  - docutils=0.20.1=py39hf3d152e_0
  - dpath=2.1.6=pyha770c72_0
  - drmaa=0.7.9=py_1000
  - dropbox=11.36.0=pyhd8ed1ab_0
  - entrez-direct=16.2=he881be0_1
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filechunkio=1.8=py_2
  - filelock=3.12.0=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - fmt=9.1.0=h924138e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_1
  - ftputil=5.0.4=pyhd8ed1ab_0
  - furl=2.1.3=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - gffread=0.12.7=hdcf5f25_3
  - gffutils=0.12=pyh7cba7a3_0
  - giflib=5.2.1=h0b41bf4_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - google-api-core=2.11.0=pyhd8ed1ab_0
  - google-api-python-client=2.87.0=pyhd8ed1ab_0
  - google-auth=2.18.1=pyh1a96a4e_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.9.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py39h8db88ab_4
  - google-resumable-media=2.5.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.1=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=2.0.2=py39h3d6467e_1
  - grpcio=1.51.1=py39h712372c_0
  - harfbuzz=6.0.0=h3ff4399_1
  - htslib=1.17=h6bc39ce_1
  - httplib2=0.22.0=pyhd8ed1ab_0
  - humanfriendly=10.0=py39hf3d152e_4
  - hypothesis=6.79.3=pyha770c72_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - infinity=1.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intervals=0.9.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39hf3d152e_0
  - k8=0.2.5=hdcf5f25_4
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libarchive=3.6.2=hc8874e4_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=h6312ad2_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.4=hebfc3b9_0
  - libgomp=12.2.0=h65d4601_19
  - libgrpc=1.51.1=h05bd8bd_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libmamba=1.2.0=habaa8ee_0
  - libmambapy=1.2.0=py39hf403a7a_0
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.21.12=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.23=h3eb15da_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h0e0dad5_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.10.4=hfdac1af_0
  - libzlib=1.2.13=h166bdaf_4
  - logmuse=0.2.6=pyh8c360ce_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mamba=1.2.0=py39hfa8f2c8_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39h72bdee0_0
  - marshmallow=3.14.1=pyhd8ed1ab_0
  - marshmallow-dataclass=8.5.3=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mikado=2.3.4=py39h919a90d_0
  - minimap2=2.26=he4a0461_1
  - miniprot=0.11=he4a0461_2
  - msgpack-python=1.0.5=py39h4b4f3f3_0
  - multidict=6.0.4=py39h72bdee0_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-connector-c=6.1.11=h6eb9d5d_1007
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.24.3=py39h6183b62_0
  - oauth2client=4.1.3=py_0
  - openjdk=17.0.3=h58dac75_5
  - openssl=1.1.1w=hd590300_0
  - orderedmultidict=1.0.1=py_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=1.4.4=py39h1832856_0
  - paramiko=3.1.0=pyhd8ed1ab_0
  - passlib=1.7.4=pyh9f0ad1d_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - pendulum=2.1.2=py39h72bdee0_5
  - peppy=0.35.5=pyhd8ed1ab_0
  - perl=5.26.2=h36c2ea0_1008
  - perl-apache-test=1.40=pl526_1
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-class-data-inheritable=0.08=pl526_1
  - perl-class-load=0.25=pl526_0
  - perl-class-load-xs=0.10=pl526h6bb024c_2
  - perl-class-method-modifiers=2.12=pl526_0
  - perl-clone-choose=0.010=pl526_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-data-optlist=0.110=pl526_2
  - perl-db_file=1.855=pl5262h7f98852_0
  - perl-devel-globaldestruction=0.14=pl526_0
  - perl-devel-overloadinfo=0.005=pl526_0
  - perl-devel-stacktrace=2.04=pl526_0
  - perl-dist-checkconflicts=0.11=pl526_2
  - perl-encode=2.88=pl526_1
  - perl-eval-closure=0.14=pl526h6bb024c_4
  - perl-exception-class=1.44=pl526_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-getopt-long=2.50=pl526_1
  - perl-hash-merge=0.300=pl526_0
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-list-util=1.38=pl526_1
  - perl-math-utils=1.13=pl526_0
  - perl-mce=1.837=pl526_0
  - perl-mime-base64=3.15=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_1
  - perl-module-runtime-conflicts=0.003=pl526_0
  - perl-moo=2.003004=pl526_0
  - perl-moose=2.2011=pl526hf484d3e_1
  - perl-mro-compat=0.13=pl526_0
  - perl-package-deprecationmanager=0.17=pl526_0
  - perl-package-stash=0.38=pl526hf484d3e_1
  - perl-package-stash-xs=0.28=pl526hf484d3e_1
  - perl-parallel-forkmanager=2.02=pl526_0
  - perl-params-util=1.07=pl526h6bb024c_4
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-role-tiny=2.000008=pl526_0
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-scalar-util-numeric=0.40=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-storable=3.15=pl526h14c3975_0
  - perl-sub-exporter=0.987=pl526_2
  - perl-sub-exporter-progressive=0.001013=pl526_0
  - perl-sub-identify=0.14=pl526h14c3975_0
  - perl-sub-install=0.928=pl526_2
  - perl-sub-name=0.21=pl526_1
  - perl-sub-quote=2.006003=pl526_1
  - perl-test-pod=1.52=pl526_0
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - phonenumbers=8.13.15=pyhd8ed1ab_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plac=1.3.5=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - portcullis=1.2.4
  - prettytable=3.7.0=pyhd8ed1ab_0
  - prodigal=2.6.3=h031d066_6
  - prot-scriber=0.1.5=h031d066_0
  - protobuf=4.21.12=py39h227be39_0
  - psutil=5.9.5=py39h72bdee0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.7.0=py39hf3d152e_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.4=py39hb9d737c_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyfaidx=0.7.2.1=pyh7cba7a3_1
  - pygments=2.15.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py39hb9d737c_2
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py39h72bdee0_0
  - pysam=0.21.0=py39h9abd093_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.3.1=pyhd8ed1ab_0
  - python=3.9.15=h47a2c10_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-irodsclient=1.1.8=pyhd8ed1ab_0
  - python-rapidjson=1.10=py39h227be39_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2023.3=pyhd8ed1ab_0
  - pytzdata=2020.1=pyh9f0ad1d_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0=py39hb9d737c_5
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.31.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.3.5=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.17.26=py39hd1e30aa_0
  - ruamel.yaml.clib=0.2.7=py39h72bdee0_1
  - s3transfer=0.6.1=pyhd8ed1ab_0
  - samtools=1.17=hd87286a_1
  - scipy=1.10.1=py39h6183b62_3
  - setuptools=67.7.2=pyhd8ed1ab_0
  - simplejson=3.19.1=py39h72bdee0_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.3.0=pyhd8ed1ab_1
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=7.26.0=hdfd78af_0
  - snakemake-minimal=7.26.0=pyhdfd78af_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlalchemy=1.4.46=py39h72bdee0_0
  - sqlalchemy-utils=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-arrow=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-babel=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-base=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-color=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-encrypted=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-intervals=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-password=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-pendulum=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-phone=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-timezone=0.41.1=pyhd8ed1ab_0
  - sqlalchemy-utils-url=0.41.1=pyhd8ed1ab_0
  - sqlite=3.42.0=h2c6b66d_0
  - star=2.7.10b=h6b7c446_1
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - stringtie=2.2.1=h6b7c446_4
  - tabulate=0.9.0=pyhd8ed1ab_1
  - throttler=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typeguard=2.13.3=pyhd8ed1ab_0
  - typing-extensions=4.6.1=hd8ed1ab_0
  - typing_extensions=4.6.1=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - ubiquerg=0.6.2=pyhd8ed1ab_0
  - ucsc-bedtogenepred=377=ha8a8165_3
  - ucsc-bedtopsl=377=ha8a8165_3
  - ucsc-genepredtogtf=377=ha8a8165_5
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wget=1.20.3=ha56f1ee_1
  - wheel=0.40.0=pyhd8ed1ab_0
  - wrapt=1.15.0=py39h72bdee0_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h27087fc_2
  - yarl=1.9.1=py39hd1e30aa_0
  - yte=1.5.1=pyha770c72_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py39h29414ee_1
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - cython==0.29.35
      - pygustus==0.8.3
